import React, { useState, useEffect } from "react";
import { motion } from "motion/react";
import { 
  BadgeDollarSign, 
  Download 
} from "lucide-react";
import { storage } from "../lib/storage";
import { StatusBadge } from "./Dashboard";

export default function ClosedDeals() {
  const [closedLeads, setClosedLeads] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchClosedDeals = () => {
      const allLeads = storage.getLeads();
      const filteredLeads = allLeads.filter(l => ["closed", "rejected", "cancelled"].includes(l.status));
      
      const allProposals = storage.getProposals();
      
      const leadsWithProposals = filteredLeads.map(lead => {
        const proposal = allProposals.find(p => p.leadId === lead.id);
        return { ...lead, proposal };
      });

      setClosedLeads(leadsWithProposals);
      setLoading(false);
    };

    fetchClosedDeals();
    const interval = setInterval(fetchClosedDeals, 2000);
    return () => clearInterval(interval);
  }, []);

  const downloadInvoice = (lead: any, proposal: any) => {
    if (!proposal) return;
    const subtotal = proposal.basePrice * (lead.userCount || 1);
    const discountAmount = subtotal * (proposal.discountPercent / 100);
    const finalMonthly = subtotal - discountAmount;
    const yearlyTotal = finalMonthly * 12;

    const content = `
============================================================
              SALESPILOT: OFFICIAL INVOICE
============================================================
INVOICE ID: INV-${proposal.id.slice(0, 8).toUpperCase()}
DATE: ${new Date().toLocaleDateString()}
DUE DATE: ${new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}

BILL TO:
Name: ${lead.contactName || "Executive"}
Entity: ${lead.companyName}
Contact: ${lead.email || "N/A"}

------------------------------------------------------------
DESCRIPTION                    QTY       PRICE      TOTAL
------------------------------------------------------------
${proposal.toolName} Subscription   ${lead.userCount || 1}       $${proposal.basePrice.toFixed(2)}    $${subtotal.toFixed(2)}

------------------------------------------------------------
SUBTOTAL:                                          $${subtotal.toFixed(2)}
DISCOUNT (${proposal.discountPercent}%):                                   -$${discountAmount.toFixed(2)}
------------------------------------------------------------
MONTHLY TOTAL:                                     $${finalMonthly.toFixed(2)}
ANNUAL TOTAL:                                      $${yearlyTotal.toFixed(2)}

TERMS & CONDITIONS:
- Team Seats: ${lead.userCount || 1}
- Billing Cycle: Monthly
- ${proposal.terms}

PAYMENT STATUS: PAID
GENERATED BY: SALESPILOT
============================================================
    `;
    const blob = new Blob([content.trim()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `INVOICE_${lead.companyName.toUpperCase().replace(/\s+/g, '_')}.txt`;
    a.click();
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="eyebrow-label block mb-1">Settlement Ledger</span>
          <h2 className="font-serif text-2xl text-[#0E0D0C] font-normal">Invoices & Settled Transactions</h2>
        </div>
        <div className="text-xs text-[#6B6862]">
          Financial archive and payment records
        </div>
      </div>

      <div className="luxury-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left min-w-[700px]">
            <thead className="bg-[#FFFFFF] text-[#6B6862] font-normal border-b border-[#E5E4E1]">
              <tr>
                <th className="px-6 py-3.5 eyebrow-label">Order Ref</th>
                <th className="px-6 py-3.5 eyebrow-label">Client</th>
                <th className="px-6 py-3.5 eyebrow-label">Service Allocation</th>
                <th className="px-6 py-3.5 eyebrow-label">Pricing & Terms</th>
                <th className="px-6 py-3.5 eyebrow-label">Status</th>
                <th className="px-6 py-3.5 eyebrow-label text-right">Invoice</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E5E4E1] bg-[#FFFFFF]/50">
              {loading ? (
                <tr>
                   <td colSpan={6} className="px-6 py-10 text-center text-[#6B6862] italic">Loading records...</td>
                </tr>
              ) : closedLeads.length === 0 ? (
                <tr>
                   <td colSpan={6} className="px-6 py-10 text-center text-[#6B6862]">No settlement records found.</td>
                </tr>
              ) : (
                closedLeads.map((lead) => (
                  <tr key={lead.id} className="hover:bg-[#FFFFFF] transition-colors group">
                    <td className="px-6 py-4 font-mono text-[11px] text-[#6B6862]">
                      INV-{lead.id.slice(0, 8).toUpperCase()}
                    </td>
                    <td className="px-6 py-4">
                      <div className="font-medium text-[#0E0D0C]">{lead.companyName}</div>
                      <div className="text-[11px] text-[#6B6862]">{lead.contactName || "Direct Contact"}</div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="text-[#0E0D0C] font-medium">{lead.toolName || "Enterprise CRM"}</div>
                      <div className="text-[11px] text-[#6B6862]">{lead.userCount} Seats</div>
                    </td>
                    <td className="px-6 py-4">
                      {lead.proposal ? (
                        <>
                          <div className="font-serif text-sm text-[#0E0D0C]">${lead.proposal.finalPrice.toFixed(2)}<span className="text-[11px] font-sans text-[#6B6862]">/mo</span></div>
                          <div className="text-[11px] text-[#C9B183]">{lead.proposal.discountPercent}% Negotiated Discount</div>
                        </>
                      ) : (
                        <div className="text-[#6B6862]">Standard terms</div>
                      )}
                    </td>
                    <td className="px-6 py-4">
                      <StatusBadge status={lead.status} />
                    </td>
                    <td className="px-6 py-4 text-right">
                      {lead.status === 'closed' && lead.proposal && (
                        <button 
                          onClick={() => downloadInvoice(lead, lead.proposal)}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-[#E5E4E1] bg-transparent text-[#6B6862] hover:text-[#0E0D0C] hover:border-[#0E0D0C]/30 rounded-lg text-xs transition-all cursor-pointer"
                          title="Download Invoice"
                        >
                          <Download size={13} strokeWidth={1.5} />
                          <span>PDF / Text</span>
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
